import { Inter } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={`${inter.className} scrollbar`}>{children}</body>
      </AppProvider>
    </html>
  );
}
